### ISSUE TITLE
Support iPad Landscape

### ISSUE THREAD

**Issue by dungi** [Minitour/AZDialogViewController#1]
Hello,

I just removed the FixedNavigationController in my Projekt, but the Dialogs are too wide and big on iPads in Landscape. Portrait is okay on both devices.

thanks

**Comment by Minitour** [comment]
@dunqi Hi, 

The dialog is meant to be used in portrait mode only, however, if you wish to display it in landscape, what you can do is modify the local variable [`side`](https://github.com/Minitour/AZDialogViewController/blob/master/Sources/AZDialogViewController.swift#L151)

`side` is supposed to be 1:8 of the width of the view controller, you can modify this and give it another aspect ratio, or even give it a fixed constant.

I will try in the future to support for landscape support for universal devices.

Thank you for your feedback.

**Comment by Minitour** [comment]
@dunqi 
This issue should be resolved with `1.1.2` version.

**Comment by dungi** [comment]
Thanks 😉
