### ISSUE TITLE
Custom design options

### ISSUE THREAD

**Issue by Wndworks** [Minitour/AZDialogViewController#10]
Is it possible to design the title, the message and the dialog size? The only options i see are the button styles.

**Comment by Minitour** [comment]
@Wndworks 

You can modify the font and font size:

```swift
DialogViewController(
                     titleFontSize: CGFloat = 0,
                     messageFontSize: CGFloat = 0,
                     fontName: String = "AvenirNext-Medium",
                     boldFontName: String = "AvenirNext-DemiBold"
)
```

If you wish to gain more control over the labels you are gonna have to modify the source code:

Change the access modifier  from `fileprivate` to `public` or `open`
```swift
fileprivate var titleLabel: UILabel!
fileprivate var messageLabel: UILabel!
```

**Comment by Wndworks** [comment]
@Minitour 

Allright, i can deal with that. Thanks for the fast reply!
