### ISSUE TITLE
Pod - Unable to find a specification for 'AZDialogView'

### ISSUE THREAD

**Issue by thephatp** [Minitour/AZDialogViewController#12]
For some reason, can't install the pod. I get the following error:

`[!] Unable to find a specification for 'AZDialogView' `

Is it compatible with iOS 10.0?

**Comment by Minitour** [comment]
@thephatp Last time I checked, it works perfectly fine, however I will look into this.

**Comment by Minitour** [comment]
@thephatp Also try using ```pod update```
