### ISSUE TITLE
Its not display above Tabbar.

### ISSUE THREAD

**Issue by pratik1311** [Minitour/AZDialogViewController#16]
Hi

I want to display this pop-up above the tabbar.

Like want to display popup in top of the all views.

Thanks

**Comment by Minitour** [comment]
```swift
let tabBar = self.tabBarController!
dialog.show(in: tabBar)
```

**Comment by pratik1311** [comment]
I did but tabbar is not UIViewController thats why gives error.

**Comment by Minitour** [comment]
According to Appls’s Documentation, UITabBarController is a subclass of UIViewController therefore it should work.

**Comment by pratik1311** [comment]
its not working my Friend.

**Comment by Minitour** [comment]
@pratik1311 Are you using a custom tab bar framework?
