### ISSUE TITLE
Multiline action buttons

### ISSUE THREAD

**Issue by sgtlagrange** [Minitour/AZDialogViewController#17]
Is there a way to have multiline action buttons (useful if action title is based on user input)?

**Comment by Minitour** [comment]
@sgtlagrange Hi,

You should already be able to do that, Here is how:

```swift
//create dialog
        let dialog = AZDialogViewController(title: "Some title",message: "This is a dialog")
//apply custom style for action buttons
        dialog.buttonStyle = { (button,height,index) in
            button.titleLabel?.lineBreakMode = .byWordWrapping
            button.titleLabel?.textAlignment = .center
        }
//add your actions
        dialog.addAction(AZDialogAction(title: "Line 1\nLine2") { (dialog) -> (Void) in

        })
//show when ready
        dialog.show(in: self)
```

## Result
<img width="257" alt="screen shot 2017-11-18 at 15 54 47" src="https://user-images.githubusercontent.com/17438617/32980972-dfab2666-cc78-11e7-9d9f-2d06da1dae16.png">

**Comment by sgtlagrange** [comment]
It's true you can put multiple lines, but what I meant is for the buttons to adjust their individual heights based on the content, to avoid something like this:

![screen shot 2017-11-18 at 15 01 55](https://user-images.githubusercontent.com/12433547/32981020-d4ef36c4-cc71-11e7-96f8-69c7bae81dbc.png)

Is there a way to achieve this?

**Comment by Minitour** [comment]
@sgtlagrange I see. At this point I would recommend you use the custom view container meant for containing your custom views.

You can use it like so:

```swift
dialog.container.addSubView(/*your custom view (maybe use UITableView)*/)
dialog.customViewSizeRatio = 0.5
```

**Comment by sgtlagrange** [comment]
Thanks, I'll give it a try.
