### ISSUE TITLE
Bluring the chrome

### ISSUE THREAD

**Issue by CoderXpert** [Minitour/AZDialogViewController#19]
It would be nice to have functionality where we can blur the background chrome of alert.

**Comment by Minitour** [comment]
Added in version `1.2.1`.

```swift
//true by default
dialog.blurBackground = true

//default is dark
dialog.blurEffectStyle = .extraLight
```

**Comment by CoderXpert** [comment]
I can create pr for this one as well if you haven't yet implemented. If done :shipit:

**Comment by Minitour** [comment]
@CoderXpert I have already implemented it, just make sure to test it to see if it function as you were expecting.

**Comment by CoderXpert** [comment]
thanks will do.
