### ISSUE TITLE
Unable to set font and max height on dialog view

### ISSUE THREAD

**Issue by aabiabdallah** [Minitour/AZDialogViewController#2]
If I add a large number of actions the underlying stackView flows beyond the screen.

**Comment by Minitour** [comment]
@aabiabdallah That is because the dialog doesn't have a built in scroll view.

**Comment by HackShitUp** [comment]
@aabiabdallah that's just bad design

**Comment by hemangshah** [comment]
@HackShitUp, that's not a bad design, the `AZDialogViewController` is created to present few options to the user and not the multiple options thus the users will be confused on scrolling the `AZDialogViewController`. @aabiabdallah, if it requires you can show few options and then by choosing any of the options, you can create (and show) another dialog with different options. This is more convenient for your need. @Minitour, very well work 👍

**Comment by Minitour** [comment]
@hemangshah Thanks 😏 , @aabiabdallah Like hemangshah suggested, you can show different actions based on the action the user has selected. In fact you don't have to show a new dialog, you can use `removeAction(at:)` and then use `addAction()`.

**Comment by aabiabdallah** [comment]
@hemangshah, thank you for the suggestion. The usage scenario I had was a switch account feature. Users with multiple accounts complained they are unable to see/scroll all their accounts. Thus the suggestion to add a scroll view. Showing another dialog isn't a valid solution in this case.

**Comment by Minitour** [comment]
@aabiabdallah If you want you can use the `container` (custom view) and place a table view within it.

**Comment by Minitour** [comment]
@aabiabdallah more over on what I said in my last comment, here is how you add a table view, something that you couldn't have done before version 1.1.3:

```swift
       let dialog = AZDialogViewController(title: "Switch Account", message: nil)
        
        dialog.showSeparator = false
        
        let container = dialog.container
        
        dialog.customViewSizeRatio = 1.0
        
        let tableView = UITableView(frame: .zero, style: .plain)
        
        container.addSubview(tableView)
        
        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "cell")
        
        tableView.delegate = self
        tableView.dataSource = self
        tableView.separatorColor = .clear
        
        tableView.translatesAutoresizingMaskIntoConstraints = false
        tableView.topAnchor.constraint(equalTo: container.topAnchor).isActive = true
        tableView.bottomAnchor.constraint(equalTo: container.bottomAnchor).isActive = true
        tableView.leftAnchor.constraint(equalTo: container.leftAnchor).isActive = true
        tableView.rightAnchor.constraint(equalTo: container.rightAnchor).isActive = true
        
        
        dialog.show(in: self)
```

Delegate and Data Source:
```swift
extension ViewController: UITableViewDelegate{
    public func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        //do something
    }
}

extension ViewController: UITableViewDataSource{
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return items.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let cell = tableView.dequeueReusableCell(withIdentifier: "cell"){
            cell.textLabel?.text = items[indexPath.row]
            return cell
        }
        return UITableViewCell()
    }
}
```

**Comment by aabiabdallah** [comment]
@Minitour, thank you for the suggestion. I will give it a try.

**Comment by hemangshah** [comment]
@aabiabdallah, yes you're right, for your case, you need something which is scrollable. 👍

**Comment by HackShitUp** [comment]
@hemangshah you don't want to give people too many options. Too many options == bad design.

**Comment by Minitour** [comment]
@aabiabdallah Were you able to resolve your issue?
