### ISSUE TITLE
Unable to customize UIButton.

### ISSUE THREAD

**Issue by HackShitUp** [Minitour/AZDialogViewController#21]
I've been trying to modify the AZDialogView's buttons to make them look like the default iOS alert controllers (with a button image in it), but with the gesture-dismissing capabilities of this project. But, I can't customize the button for some reason. Here's my code:
``` swift
// Configure UIButton styles
        dialogController.buttonStyle = { (button, height, position) in
            // Fill button with color
            button.setImage(UIImage(named: "pop"), for: .normal)
            button.semanticContentAttribute = .forceLeftToRight
            button.titleLabel?.font = UIFont(name: "AvenirNext-Demibold", size: 16)
            button.layer.masksToBounds = true
        }
```

**Comment by Minitour** [comment]
@HackShitUp Thanks for bringing up the issue. At the moment the buttons are initialized using the `UIButton` class without any special sub-classing capabilities. I will add a new property in the future to allow using custom `UIButton` sub classes. 

Add this line to remove the border:
```swift
button.layer.borderColor = UIColor.clear.cgColor
```

**Comment by HackShitUp** [comment]
@Minitour awesome, thanks a lot

**Comment by Minitour** [comment]
@HackShitUp I added some new APIs in version `1.2.1`. 
One of them is called `buttonInit`, a closure that allows you to use a custom UIButton sub-class.

Example:
```swift
dialog.buttonInit = { index in
    //set a custom button only for the first index
    return index == 0 ? HighlightableButton() : nil
}
```
If a nil value is returned then the default button that was used in the previous versions of the framework will be created.
