### ISSUE TITLE
Change font of title and message labels

### ISSUE THREAD

**Issue by ramonsgds** [Minitour/AZDialogViewController#22]
I am being able to change font of cancel button and action buttons just fine.

When it comes to changing title and message label fonts, I can't, since it's fileprivate.

Could you release a new version with these two small functions, enabling us to change message label and title label fonts?

**Comment by Minitour** [comment]
@ramonsgds 
In the convenience initialiser  there are the following optional params:
`fontName` - used for the message
`boldFontName` - used for the title

```swift
public convenience init(title: String?=nil,
                     message: String?=nil,
                     verticalSpacing spacing: CGFloat = -1,
                     buttonSpacing stackSpacing:CGFloat = 10,
                     sideSpacing: CGFloat = 20,
                     titleFontSize: CGFloat = 0,
                     messageFontSize: CGFloat = 0,
                     buttonsHeight: CGFloat = 0,
                     cancelButtonHeight: CGFloat = 0,
                     fontName: String = "AvenirNext-Medium",
                     boldFontName: String = "AvenirNext-DemiBold"){
...
}
```

You can use it like so:
```swift
AZDialogViewController(fontName: "Helvetica",
                     boldFontName: "Helvetica-Bold")
```

I will be adding a way to access the labels in the future.
