### ISSUE TITLE
Change font size?

### ISSUE THREAD

**Issue by mattpidd** [Minitour/AZDialogViewController#25]
When I present the alert view the fonts are both pretty small. I tried:
`dialog.titleFontSize = CGFloat(30.0)` however it gives me an error saying that titleFontSize setter is inaccessible.

**Comment by Minitour** [comment]
You can modify the font only using the initializer.

**Comment by mattpidd** [comment]
Could you please provide an example? Thanks

**Comment by Minitour** [comment]
See issue #22

**Comment by mattpidd** [comment]
<img width="910" alt="screen shot 2018-03-03 at 10 39 31" src="https://user-images.githubusercontent.com/35871546/36933356-44316af2-1ecf-11e8-81d7-f0ad201694bb.png">

**Comment by Minitour** [comment]
@mattpidd this should get the job done, Although I don’t recommend going crazy with the sizes.

**Comment by mattpidd** [comment]
<img width="356" alt="screen shot 2018-03-03 at 10 43 52" src="https://user-images.githubusercontent.com/35871546/36933385-c914fa9a-1ecf-11e8-8e98-f2c25f011a63.png">

**Comment by Minitour** [comment]
🤔 I will look into it

**Comment by mattpidd** [comment]
Ok, thanks!

**Comment by mattpidd** [comment]
any progress?

**Comment by mattpidd** [comment]
Have you found anything/fixed it?

**Comment by Minitour** [comment]
@mattpidd Hey,
I still haven't had the chance to dig into it due to other projects I am currently occupied with. I will get on to it this weekend however. stay tuned for updates.

**Comment by Minitour** [comment]
@mattpidd I just tried the code and it works perfectly fine. Perhaps you are doing something wrong or maybe you are using an outdated version?

<img src="https://user-images.githubusercontent.com/17438617/37169805-a529d830-2311-11e8-80a2-762db4141c0d.png" width="240"/>

```swift
let dialog = AZDialogViewController(title: "Loading...", message: "Logging you in, please wait",titleFontSize: 40)
```

**Comment by mattpidd** [comment]
Now I feel very stupid. I wasn't changing my dialog variable. Thanks a lot, my last question is how to chnage the button font size?

**Comment by Minitour** [comment]
@mattpidd View the README here
https://github.com/Minitour/AZDialogViewController#customize-action-buttons-style

This section shows how to customize the buttons

**Comment by mattpidd** [comment]
Thanks for everything!
