### ISSUE TITLE
Dialog inside a popover 

### ISSUE THREAD

**Issue by RNUK** [Minitour/AZDialogViewController#26]
![dialogview](https://user-images.githubusercontent.com/11478756/41460442-a667ee4c-7084-11e8-87f9-e8902ca6c3e7.jpg)
I am using a popover to display an appointment diary and I am using AZDialogs to display messages in my app. This works great when presented on a phone as the popover is presented as a modal view so the width of the dialog is correct, however when displayed on an iPad (The target device) the dialog is wider than the popover window. 

I have read through other support queries here and can see that there is no support for custom widths,   but how does the width get calculated for these dialogs (overall device size at a guess?) and is there any way to get the calculation to use the displaying superview width?

**Comment by Minitour** [comment]
Hi @RNUK , The dialog container is sized proportionally based on the current device. 
Try changing the implementation of these functions:
https://github.com/Minitour/AZDialogViewController/blob/88f97e0e6e10fc5f6485f0673c562ce2596b9d4d/Sources/AZDialogViewController.swift#L125

deviceWidth,deviceHeight to bound the minimum device height/width to your liking.

**Comment by RNUK** [comment]
@Minitour thanks for the quick response. I decided to add extra variables to the class so I could explicitly say if it was in a popover or not and pass in the width of that frame. That way I could keep the basic look/feel for the dialog for normal views

`  
open var isSubView: Bool = false
open var subViewWidth: CGFloat = 0
`

`
        if self.isSubView == true {
            baseView.widthAnchor.constraint(equalToConstant: self.subViewWidth * 0.8).isActive = true
        } else {
            baseView.widthAnchor.constraint(equalToConstant: deviceWidth * 0.7).isActive = true
        }
`
