### ISSUE TITLE
UITextView for container value

### ISSUE THREAD

**Issue by HackShitUp** [Minitour/AZDialogViewController#3]
How does the .customViewSizeRatio variable resize the custom view? 
I'm adding a UITextView inside AZDialogViewController's container view.

**Comment by Minitour** [comment]
@HackShitUp 
`customViewSizeRatio` is the height ratio in respect to the width of the view.
Where the width is always gonna be the width of the dialog.

So for example if you use `customViewSizeRatio` of 0.2, the height of the container will be 20% of the width of the container.

I suggest you color the background of the container and play with the ratio to understand how it works. If you have any questions feel free to ask.

**Comment by HackShitUp** [comment]
@Minitour Thanks for your response, I was able to figure it out by setting the background color. But I think I might've found another issue with the cancel button because it doesn't show up when configured as instructed in the readme

**Comment by Minitour** [comment]
@HackShitUp The README is currently outdated, I will be updating it as soon as possible. 

Starting from version 1.2.2, to show the cancel button you will need to set the `cancelEnabled` to true. 

Link to the reference can be found [here](https://github.com/Minitour/AZDialogViewController/blob/master/Sources/AZDialogViewController.swift#L234).

**Comment by HackShitUp** [comment]
Got it! Thanks @Minitour
