### ISSUE TITLE
iPhone XS Max support?

### ISSUE THREAD

**Issue by carrarodev** [Minitour/AZDialogViewController#30]
I everyone, I've been testing AZDialogView with iPhone XS Max screen sizes, and the view controller is rendered oddly. It appears very small on the ViewController

**Comment by Minitour** [comment]
I didn't get a chance to test it on the newer models yet. I will look into it.

**Comment by carrarodev** [comment]
Thanks very much! If can help, the same happen on the XR
![schermata 2018-09-24 alle 18 17 45](https://user-images.githubusercontent.com/402719/45964584-80faa400-c026-11e8-9c7a-bffa4cb533f5.png)

**Comment by Sopheak0** [comment]
I got the same issue!

**Comment by stshelton** [comment]
I have the same issue on iPhone X, using the actual device not simulator.
