### ISSUE TITLE
Feature request: app-wide customization

### ISSUE THREAD

**Issue by rostopira** [Minitour/AZDialogViewController#32]
Add static shared property, to change default style app-wide
Good example, is default iOS components, like `UITableViewCell.appearance()` and libraries like `ToastSwift`:
```
        var toastStyle = ToastStyle()
        toastStyle.backgroundColor = UIColor.init(white: 0, alpha: 0.5)
        ToastManager.shared.style = toastStyle
```

**Comment by Minitour** [comment]
You can now use the `DialogDefaults` struct for global configuration.
