### ISSUE TITLE
Windows are too small on iPad

### ISSUE THREAD

**Issue by rostopira** [Minitour/AZDialogViewController#33]
![img_76a9e3038ed9-1](https://user-images.githubusercontent.com/16724952/47706018-3a0d5900-dc39-11e8-939b-a6d2d0724be7.jpeg)

**Comment by Minitour** [comment]
The height of the dialog is decided based on its contents.

You can now change the width of the dialog using `DialogDefaults` by doing
```swift 
DialogDefaults.widthRatio = 1.0
```
The default is 0.75

**Comment by rostopira** [comment]
Well, that's doesn't really solves the issue, now dialog is wider, but it still small
I mean text, title, button sizes
Would be great to have some sort of `scale` parameter
Interface builder has it, every constant can be set for ipad by setting regular/regular screen size

**Comment by rostopira** [comment]
Current solution for me is following values:
```swift
            DialogDefaults.widthRatio = 1
            DialogDefaults.buttonHeightRatio = 0.1
            DialogDefaults.buttonWidthRatio = 0.6
            DialogDefaults.messageFontSizeRatio = 0.04
            DialogDefaults.titleFontSizeRatio = 0.05
```
This ratios should be relative to defaults, instead of device width, IMHO

**Comment by Minitour** [comment]
@rostopira You can change the properties using the initialiser.
