### ISSUE TITLE
Dialog appears a-lot smaller on IPhone X 

### ISSUE THREAD

**Issue by stshelton** [Minitour/AZDialogViewController#35]
Having the same issue as #30 . Im using an iphone x and this is how the pop up appears. On Iphone 7-8 pop up window appears normal size. IPhone X AzdialogView's text and buttons appear alot smaller when shown on that device.

![qspr27lnspqzuyyo2zfkyw_thumb_1051](https://user-images.githubusercontent.com/11301401/51492563-50323d80-1d80-11e9-94c5-cef8a71c7940.jpg)

**Comment by Minitour** [comment]
Fixed with the new release (1.3.1)
