### ISSUE TITLE
Override height for calculations?

### ISSUE THREAD

**Issue by RNUK** [Minitour/AZDialogViewController#37]
I am using AZDialog in my project, but when I try to display a dialog in a custom modal view, the dialog is squeezed. I think this is happening because the custom modal is smaller than the screen height (music app style) - If I present this view with a normal modal presentation style, the dialog works fine. Is there any way to override the height function of the dialog without altering the core dialog view code?

![354D087F-358A-4919-86D8-932CF785734A](https://user-images.githubusercontent.com/11478756/58543160-d52dd780-81f6-11e9-8cf0-2cc8b837e09a.png)
![2B13C3BA-76BB-4291-867B-A722F2FE3A4D](https://user-images.githubusercontent.com/11478756/58543162-d52dd780-81f6-11e9-998b-cca21dce8c3a.png)

**Comment by Minitour** [comment]
@RNUK, thanks for bringing this issue to my attention, I will look into it.
For a quick fix, you can go inside the class and modify the computed variable `deviceHeight` and return a constant value in there.

**Comment by RNUK** [comment]
This was my mistake. I have updated to 1.3.4 and it works fine.
