### ISSUE TITLE
How to show dialog from top?

### ISSUE THREAD

**Issue by jdleung** [Minitour/AZDialogViewController#40]
The dialog always popup from bottom, I cannot find a way to make it popup from the top, how to do that?

Thanks.

**Comment by Minitour** [comment]
@jdleung I know this is like almost a year old post but I figured I should post the answer anyway and close this issue.

This is currently not supported and the only way to achieve this by editing the following line in the source code:
https://github.com/Minitour/AZDialogViewController/blob/d7ed39d2e3cc6eda5d4d054ff9eb24eb5ada7be1/Sources/AZDialogViewController.swift#L840

to

```swift
baseView.center.y = self.view.bounds.minY - baseView.bounds.midY 
```

**Comment by jdleung** [comment]
OK, Thanks.
