### ISSUE TITLE
Issue when Dismissing 

### ISSUE THREAD

**Issue by kishanios123** [Minitour/AZDialogViewController#41]
Dismissing Alert is also dismiss other alert which is shown after dismiss... is it because of super.dismiss when dismissing ??

Please some one let me know solution ...

**Comment by Minitour** [comment]
Did you try to present the second alert in the completion handler of the first alert?

**Comment by kishanios123** [comment]
> Did you try to present the second alert in the completion handler of the first alert?

After completion it works fine ... in other alert it is also possible to present without waiting for completion ...
