### ISSUE TITLE
Dialog Controller is covered by keyboard.

### ISSUE THREAD

**Issue by HackShitUp** [Minitour/AZDialogViewController#5]
Is there a way to reset the constraints of the dialog when the keyboard appears? The keyboard covers parts of the dialog...

**Comment by Minitour** [comment]
@HackShitUp Add an observer when the keyboard opens, and when it does set the `contentOffset` of the dialog object.

```swift
var dialog: AZDialogViewController!

func didShowKeyboard(){
       let x = //some constant
       dialog.contentOffset = x
}

```

**Comment by HackShitUp** [comment]
@Minitour Got it. Thank you!
