### ISSUE TITLE
Dialog Transparency

### ISSUE THREAD

**Issue by jimsmithm3** [Minitour/AZDialogViewController#6]
Is there a way to make the dialog use an alpha value so that I can see my image behind it?

I tried a couple of ways with the dialog and dialog.container but didn't have any luck.

**Comment by Minitour** [comment]
Hi @jimsmithm3 
Check out [this](https://github.com/Minitour/AZDialogViewController/blob/master/Sources/AZDialogViewController.swift#L594) line.

I you don't want to modify the source code you can try this:
```swift
dialog.container.superview!.superview!.layer.backgroundColor = //your CGColor with alpha
```
